name: build solution

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build WebApplication1.sln --configuration Release

      - name: Publish
        run: dotnet publish ./WebApplication1.csproj -c Release -o ./publish

      - name: Zip published files
        run: Compress-Archive -Path publish\* -DestinationPath publish.zip
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish-zip
          path: publish.zip
      
  
